# Generated by Django 5.1.6 on 2025-02-21 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True, null=True)),
                ('genre', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='top_artist/')),
            ],
        ),
    ]
