# Generated by Django 5.1.6 on 2025-02-26 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunetrack', '0002_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='album',
        ),
        migrations.RemoveField(
            model_name='song',
            name='file',
        ),
        migrations.RemoveField(
            model_name='song',
            name='uploaded_at',
        ),
        migrations.AddField(
            model_name='song',
            name='audio_url',
            field=models.CharField(default='default_audio.mp3', max_length=255),
        ),
        migrations.AddField(
            model_name='song',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='cover_images/'),
        ),
    ]
