# Generated by Django 5.1.6 on 2025-02-26 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunetrack', '0003_remove_song_album_remove_song_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
    ]
