# Generated by Django 4.2.18 on 2025-03-05 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tunetrack', '0006_remove_artist_bio_remove_artist_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='tunetrack.artist'),
        ),
    ]
