# Generated by Django 5.1.6 on 2025-03-09 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tunetrack', '0007_alter_song_artist'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topsong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Topsong/')),
            ],
        ),
        migrations.CreateModel(
            name='Tune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('genre', models.CharField(blank=True, max_length=100, null=True)),
                ('audio_url', models.FileField(upload_to='audio/')),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='cover_images/')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tunes', to='tunetrack.topsong')),
            ],
        ),
    ]
