# Generated by Django 5.1.6 on 2025-03-10 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tunetrack', '0008_topsong_tune'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tune',
            old_name='artist',
            new_name='topsong',
        ),
    ]
